### ISSUE TITLE
SEGGER J-Link Debug

### ISSUE THREAD

**Issue by calonsoecler** [OpenNuvoton/MA35D1_RTP_BSP#1]
I'm trying to debug Cortex-M4 using my J-Link JTAG debugger. I'm currently using NuEclipse on Linux
Could someone help me with this?

**Comment by ychuang3** [comment]
The debug interface of RTP M4 is SWD only, and does not support JTAG.
You can use Nuvoton NuLink2, NuLink Me, or NuLink2-Pro ICE.
