### ISSUE TITLE
Assign peripherals to CM4 (SUBM) from Linux Kernel

### ISSUE THREAD

**Issue by calonsoecler** [OpenNuvoton/MA35D1_RTP_BSP#2]
I have successfully tested to assign peripherals to CM4 through TF-A.
Now I'm wondering if it possible to assign a peripheral to CM4 from Linux kernel using kernel device tree or once the system has completely boot.
Any idea?

**Comment by ychuang3** [comment]
TF-A is running at Cortex-A35 secure-EL3 mode, while Linux kernel is running at Cortex-A35 non-secure-EL1 mode.
In MA35D1, peripheral device owners are assigned by SSPCC controller, which can be access in secure mode mode only.
That's why the IP assignment in TF-A, not Linux.
